USE [master]
GO

/****** Object:  Database [db_library]    Script Date: 6/25/2019 1:33:49 PM ******/
CREATE DATABASE [db_library]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_library', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\db_library.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_library_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\db_library_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_library].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_library] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_library] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_library] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_library] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_library] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_library] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [db_library] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_library] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_library] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_library] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_library] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_library] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_library] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_library] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_library] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_library] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_library] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_library] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_library] SET  MULTI_USER 
GO

ALTER DATABASE [db_library] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_library] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_library] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_library] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_library] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_library] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_library] SET  READ_WRITE 
GO

